name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    name: Install
    runs-on: ubuntu-latest
    env:
      JOBS: 1
      OPENRESTY_PREFIX: /usr/local/openresty
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt install -y cpanminus build-essential libncurses5-dev libpcre3-dev libreadline-dev libssl-dev perl luarocks

      - name: Install Test::Nginx
        run: |
          sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

      - name: Install OpenResty
        run: |
          wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
          sudo apt-get update
          sudo apt-get install openresty
          openresty -V
          git clone https://github.com/openresty/test-nginx.git test-nginx

      - name: Run Nginx Lua Tests
        run: |
          export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
          prove -Itest-nginx/lib -r t
